# Generated by Django 2.0.2 on 2018-05-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('DicomID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('PatientID', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=60)),
                ('SearchHistory', models.CharField(max_length=60)),
                ('UserName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('PatientID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=20)),
                ('PatientSex', models.CharField(max_length=5)),
                ('PatientBirthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('RecordID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('PatientID', models.CharField(max_length=60)),
                ('PatientEntity', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('PartInfo', models.CharField(max_length=50)),
                ('MedicalTime', models.DateField()),
            ],
        ),
    ]
