# Generated by Django 2.0.2 on 2018-06-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CT',
            fields=[
                ('CTID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('CTDate', models.DateField()),
                ('PatientID', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NodeID', models.CharField(max_length=60)),
                ('Node_x', models.FloatField()),
                ('Node_y', models.FloatField()),
                ('Node_z', models.FloatField()),
                ('Node_Inch', models.FloatField()),
                ('illjudge', models.CharField(max_length=30)),
                ('CTID', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='PatientEntity',
        ),
    ]
