# Generated by Django 2.0.2 on 2018-06-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_model', '0002_auto_20180604_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='CTID',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
